[tool.poetry]

name = "memegen-flet"
version = "0.1"
description = "Memegen.link client built with Flet."
authors = ["Jace Browning <jacebrowning@gmail.com>"]

[tool.poetry.dependencies]

python = "~3.9"

flet = "^0.1.50"
minilog = "^2.1"
requests = "^2.28.1"
universal-startfile = "^0.1"

[tool.poetry.dev-dependencies]

black = {version = "^22.6.0", allow-prereleases = true}
isort = "^5.10.1"

pyinstaller = "^5.3"
pillow = "^9.2.0"

[build-system]

requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
